layout: home
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Home sections (like orviboaustralia.com)
sections:
  - name: Hero
    title: Welcome to Vsense
    subtitle: Smarter Living, One Device at a Time
    button:
      text: Discover Products
      link: /products
    background_image: /assets/images/hero.jpg

  - name: Features
    features:
      - icon: /assets/icons/automation.svg
        title: Full Home Automation
        description: Seamlessly control lighting, climate, and security.
      - icon: /assets/icons/security.svg
        title: Enhanced Security
        description: Keep your home safe with real-time alerts and monitoring.
      - icon: /assets/icons/app.svg
        title: App Integration
        description: Manage everything from your mobile device.

  - name: Products
    title: Featured Products
    display_limit: 6
    layout: grid

  - name: Testimonials
    title: What Our Customers Say
    testimonials:
      - name: Sarah M.
        quote: "Vsense completely changed how I interact with my home."
      - name: Tom R.
        quote: "Easy to install and works flawlessly with Alexa and Google."

  - name: Contact
    title: Get In Touch
    description: Reach out to us for business or support inquiries.
    form:
      action: /contact
      method: post

projects:
  sort_by: pushed
  limit: 6
  exclude:
    archived: false
    forks: true

social_media:
  facebook: vsense.official
  instagram: vsense.tech
  linkedin: company/vsense
  youtube: vsensechannel
  website: https://vsense.io

topics:
  - name: Smart Home
    web_url: https://github.com/topics/smart-home
    image_url: https://example.com/icons/smart-home.png

  - name: IoT
    web_url: https://github.com/topics/iot
    image_url: https://example.com/icons/iot.png

  - name: Automation
    web_url: https://github.com/topics/automation
    image_url: https://example.com/icons/automation.png
