layout: home
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true

sections:
  - name: Hero
    title: Welcome to Vsense
    subtitle: Smarter Living, One Device at a Time
    button:
      text: Explore Products
      link: /products
    background_image: /assets/images/hero.jpg

  - name: Features
    features:
      - icon: /assets/icons/automation.svg
        title: Full Home Automation
        description: Seamlessly control lighting, climate, and security.
      - icon: /assets/icons/security.svg
        title: Enhanced Security
        description: Keep your home safe with real-time alerts and monitoring.
      - icon: /assets/icons/integration.svg
        title: App & Voice Integration
        description: Works with Alexa, Google, and Apple HomeKit.

  - name: Product Showcase
    title: Featured Products
    layout: grid
    limit: 6

  - name: Testimonials
    title: What Our Customers Say
    testimonials:
      - name: Sarah M.
        quote: "Vsense completely changed how I interact with my home."
      - name: Tom R.
        quote: "Easy to install and works flawlessly with Alexa and Google."

  - name: Video
    video_url: https://www.youtube.com/embed/demo123
    title: See Vsense in Action

  - name: Contact
    title: Get In Touch
    form:
      action: /contact
      method: post
    address: 123 Smart St, Auckland, NZ
    phone: "+64 21 000 0000"
    email: support@vsense.io

social_media:
  facebook: vsense.official
  instagram: vsense.tech
  linkedin: company/vsense
  youtube: vsensechannel
  website: https://vsense.io

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
