layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true

sections:
  - name: Hero
    title: Smart Life with Vsense
    subtitle: Make life simpler and better with innovative technology, products and design.
    button:
      text: Discover More
      link: /products
    background_image: /assets/images/hero-socket.jpg

  - name: Product Menu
    dropdown:
      title: Products
      items:
        - Smart Door Lock C1
        - Smart Door Lock T1
        - Mixpad X Smart Panel
        - Mixpad 7 Ultra Smart Panel
        - Mixpad 7 Multifunctional Control Panel
        - Mixpad 5
        - Allone
        - Security Kit
        - ZigBee Mini Hub
        - ZigBee Smart Switch
        - B25AUS Smart Socket
        - In-wall Switch
        - Motion Sensor
        - Smart Curtain Motor
        - Magic Cube
        - Door Sensor
        - Temperature and Humidity Sensor
        - WiFi Camera

  - name: Product Showcase
    title: Explore Our Products
    layout: grid
    limit: 12

  - name: About
    title: About Vsense
    content: "We bring intelligent living into your home through seamless, innovative solutions."

  - name: Contact
    title: Get In Touch
    form:
      action: /contact
      method: post
    address: 123 Smart St, Auckland, NZ
    phone: "+64 21 000 0000"
    email: support@vsense.io

social_media:
  facebook: vsense.official
  instagram: vsense.tech
  linkedin: company/vsense
  youtube: vsensechannel
  website: https://vsense.io

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
